# Generated by Django 3.0.7 on 2020-10-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=512)),
                ('linked_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banksubscription',
            name='limited_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CorporationMembership',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.IntegerField(choices=[(1, 'Plain membership'), (2, 'Membership with funds access'), (3, 'Membership with funds & '), (4, 'Excecutive (funds, list of members)')], default=1)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.Corporation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='corporation',
            name='members',
            field=models.ManyToManyField(related_name='corporate_membership', through='banking.CorporationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankUserSubscriptionIntermediary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.BankSubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='banksubscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', through='banking.BankUserSubscriptionIntermediary', to=settings.AUTH_USER_MODEL),
        ),
    ]
