# Generated by Django 3.0.7 on 2020-10-27 19:27

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20201027_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksubscription',
            name='subscription_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=12, null=True, unique=True),
        ),
    ]
