# Generated by Django 3.0.7 on 2021-01-21 15:03

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20201027_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankusersubscriptionintermediary',
            name='subscription_request_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corporationmembership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Plain membership'), (2, 'Membership with funds access'), (3, 'Membership with funds & list of members'), (4, 'Excecutive (funds, list of members, status changes)')], default=1),
        ),
    ]
