# Generated by Django 3.0.7 on 2021-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20210121_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksubscription',
            name='extraction_period',
            field=models.IntegerField(choices=[(6, 'Раз на шість годин'), (12, 'Раз на дванадцять годин'), (24, 'Раз на двадцять чотири години')], default=24),
        ),
        migrations.AlterField(
            model_name='corporationmembership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Членство'), (2, 'Членство з доступом до фінансів'), (3, 'Членство з доступом до фінансів та списку учасників'), (4, 'Повне необмежене членство')], default=1),
        ),
    ]
