# Generated by Django 3.0.7 on 2020-10-25 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MisconductType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=512)),
                ('misconduct_code', models.CharField(max_length=8)),
                ('suggested_penalty', models.DecimalField(decimal_places=1, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MisconductReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('misconduct_status', models.IntegerField(choices=[(0, 'Report sent'), (1, 'Report revised'), (2, 'Report declined'), (3, 'Report is being processed'), (4, 'Report is finished')], default=0)),
                ('penalty_amount', models.DecimalField(decimal_places=1, max_digits=12, null=True)),
                ('penalty_status', models.IntegerField(choices=[(0, 'Penalty open'), (1, 'Penalty is active'), (2, 'Penalty is paid')], default=0)),
                ('misconduct_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_misconducts', to='law_enforcement.MisconductType')),
                ('officer_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_misconducts', to=settings.AUTH_USER_MODEL)),
                ('reported_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconduct_record', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_misconducts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
