# Generated by Django 3.0.7 on 2020-10-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0002_auto_20201025_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconductreport',
            name='penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='misconducttype',
            name='suggested_penalty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
    ]
