# Generated by Django 3.0.7 on 2021-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_enforcement', '0004_misconductreport_misconduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misconductreport',
            name='misconduct_status',
            field=models.IntegerField(choices=[(0, 'Скаргу надіслано'), (1, 'Скаргу розглянуто'), (2, 'Скаргу відхилено'), (3, 'Скарга у обробці'), (4, 'Скаргу закрито')], default=0),
        ),
        migrations.AlterField(
            model_name='misconductreport',
            name='penalty_status',
            field=models.IntegerField(choices=[(0, 'Стягнення не опрацьоване'), (1, 'Стягнення у процесі опрацювання'), (2, 'Стягнення сплачено'), (3, 'Скаргу закрито без сплати Стягнення')], default=0),
        ),
    ]
