# Generated by Django 3.0.7 on 2020-06-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bank_account',
            field=models.DecimalField(decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='character_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_hacker',
            field=models.BooleanField(default=False, help_text='Designates whether this user should have access to hacker functionality.', verbose_name='hacker'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_police',
            field=models.BooleanField(default=False, help_text='Designates whether this user should have access to police functionality.', verbose_name='police'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_security',
            field=models.BooleanField(default=False, help_text='Designates whether this user should have access to security functionality.', verbose_name='security'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user should have access to game functionality.', verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='place_of_work',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='police_comment_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='security_comment_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='telegram_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
