# Generated by Django 3.0.7 on 2020-10-25 14:47

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200618_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_service_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='character_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, lowercase=True, null=True, unique=True),
        ),
    ]
