# Generated by Django 3.0.7 on 2020-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201025_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='defence_level',
            field=models.IntegerField(default=0),
        ),
    ]
