# Generated by Django 3.0.7 on 2020-10-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_defence_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_corporate_fiction_account',
            field=models.BooleanField(default=False, help_text='Designates whether this user is pure corporative fiction', verbose_name='hacker'),
        ),
    ]
