# Generated by Django 3.0.7 on 2020-10-27 19:18

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201026_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='character_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=6, null=True, unique=True),
        ),
    ]
