# Generated by Django 3.0.7 on 2020-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201027_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='complex_service_acc',
            field=models.BooleanField(default=False, help_text='Designates whether has ComplexHack property', verbose_name='service acc'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_corporate_fiction_account',
            field=models.BooleanField(default=False, help_text='Designates whether this user is pure corporative fiction', verbose_name='corporative fiction'),
        ),
    ]
