# Generated by Django 3.0.7 on 2021-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201028_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='has_special_hack_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='special_hack_pro_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='system_heat',
            field=models.IntegerField(default=0),
        ),
    ]
