# Generated by Django 3.0.7 on 2021-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210123_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_fiction_account',
            field=models.BooleanField(default=False),
        ),
    ]
