# Generated by Django 3.0.7 on 2021-03-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_useraccount_is_fiction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='custom_hack_beginning_text_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='custom_special_hack_text_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_warned_of_hack_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='requests_made_since_last_purge',
            field=models.IntegerField(default=0),
        ),
    ]
