# Generated by Django 3.0.7 on 2021-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210303_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_warned_of_hacker',
            field=models.BooleanField(default=False),
        ),
    ]
