# Generated by Django 3.0.7 on 2021-03-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraccount_is_warned_of_hacker'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='video_to_send_to_hacker',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
