# Generated by Django 3.0.7 on 2021-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_useraccount_video_to_send_to_hacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='video_to_send_to_hacker',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
