# Generated by Django 3.0.7 on 2022-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210305_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='frozen_sum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='major_secret_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='minor_secret_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
    ]
